//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5446
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gunaydininsaattahahut {
    
    
    public partial class hizmetlerimiz_page_1 {
        
        /// <summary>
        /// hizmetlerimiz_page_11 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::gunaydininsaattahahut.hizmetlerimiz_page_11 hizmetlerimiz_page_11;
    }
}
